MERGE INTO RATINGMPA(MPA_ID, MPA_NAME) VALUES (1, 'G');
MERGE INTO RATINGMPA(MPA_ID, MPA_NAME) VALUES (2, 'PG');
MERGE INTO RATINGMPA(MPA_ID, MPA_NAME) VALUES (3, 'PG-13');
MERGE INTO RATINGMPA(MPA_ID, MPA_NAME) VALUES (4, 'R');
MERGE INTO RATINGMPA(MPA_ID, MPA_NAME) VALUES (5, 'NC-17');

MERGE INTO GENRES(GENRE_ID, GENRE_NAME) VALUES (1, 'Фантастика');
MERGE INTO GENRES(GENRE_ID, GENRE_NAME) VALUES (2, 'Драма');
MERGE INTO GENRES(GENRE_ID, GENRE_NAME) VALUES (3, 'Военный');
MERGE INTO GENRES(GENRE_ID, GENRE_NAME) VALUES (4, 'Триллер');
MERGE INTO GENRES(GENRE_ID, GENRE_NAME) VALUES (5, 'Документальный');
MERGE INTO GENRES(GENRE_ID, GENRE_NAME) VALUES (6, 'Боевик');
MERGE INTO GENRES(GENRE_ID, GENRE_NAME) VALUES (7, 'Комедия');

